/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Wild Arms)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80026F54u
#define func_80026F54 BootEntry  /* alias */
